### ISSUE TITLE
安装出现异常

### ISSUE THREAD

**Issue by 82826666** [jqhph/swoft-admin#1]
- Swoft Version: #.#.#
- Swoole Version: #.#.#
- PHP Version: #.#.#
- Laravel-admin: #.#.#

### Steps To Reproduce:
composer require lldca/swoft-admin
提示：
 [Composer\Json\JsonValidationException]                     
  "./composer.json" does not match the expected JSON schema:  
   - homepage : Invalid URL format

**Comment by jqhph** [comment]
目前swoft1.0版本对第三方组件支持不太友好，swoft-admin的安装比较繁琐了一些。我现在上传了集成版代码，只需要下载下来 composer install就能使用了：
https://github.com/jqhph/swoft-admin-auto
